name: Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Clone this repositories "build" branch
    - name: Clone this repositories "build" branch
      uses: actions/checkout@v2
      with:
        token: ${{ secrets['GH_PAT'] }}
        ref: build

    # Merge changes from the main branch into the "build" branch
    - name: Merge main branch into "build" branch
      uses: devmasx/merge-branch@v1.3.1
      with:
        type: now
        from_branch: master
        target_branch: build
        github_token: ${{ secrets['GH_PAT'] }}

    # Setup some Node.js stuff
    - name: Node.js setup
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Setup GitHub SSH key so we can npm install GitHub repositories (even needed for public ones)
    - name: GitHub SSH setup
      uses: webfactory/ssh-agent@master
      with:
        ssh-private-key: ${{ secrets['GH_SSH'] }}

    # Install NPM dependencies and build
    - name: Install NPM dependencies and build
      run: |
        npm ci
        node cmd.js -c dashboard -s ci
        npm run build

    # Commit newly built files
    - name: Commit built files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -f ':(glob)./*/*/dist/**' ':(exclude)node_modules'
        git commit -m "Built files" -a

    # Pushes the built files
    - name: Push built files
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets['GH_PAT'] }}
        branch: build
